version: "3"
services:
  ups-logger2:
    build: .
    image: nutgraf
    environment:
      - NUT_HOST=${NUT_HOST}
      - NUT_PORT=${NUT_PORT}
      - NUTGRAF_LOGGING_URL=${LOGGING_URL}
    container_name: nutgraf
    restart: always
